# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ExportToGPKG
                                 A QGIS plugin
 Export layers to a gpkg file
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-07-14
        copyright            : (C) 2018 by DodoIta
        email                : davide.cor94@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ExportToGPKG class from file ExportToGPKG.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .export_to_gpkg import ExportToGPKG
    return ExportToGPKG(iface)
